### ISSUE TITLE
Dark mode feature

### ISSUE THREAD

**Issue by LangaLee** [sidendev/nc-news-react#12]
<img width="1512" alt="image" src="https://github.com/sidendev/nc-news-react/assets/146188477/ec742a33-5f21-4b65-adcf-a42c69280536">
pleae add dark mode

**Comment by sidendev** [comment]
We now have light and dark mode at last. 
![light-dark-mode](https://github.com/user-attachments/assets/b83ba5c5-955a-40cc-a124-3d41ca8ea1ab)
