### ISSUE TITLE
Voting infinitely

### ISSUE THREAD

**Issue by LangaLee** [sidendev/nc-news-react#13]
https://github.com/sidendev/nc-news-react/assets/146188477/fc0d27f2-e7d8-4df5-8563-25f1ae99e45e

Voting currently is infinite can we fix this 😢

**Comment by sidendev** [comment]
This has been updated now, you need to be logged in to make any vote and a user can only vote once per article. 
![votes-screenshot](https://github.com/user-attachments/assets/c8edbc39-7db5-4a67-a302-c16b834f5ebc)
